### ISSUE TITLE
🆘site build报错

### ISSUE THREAD

**Issue by paleface001** [antvis/gatsby-theme-antv#103]
从最新的0.10.42到0.10.0都不行，错误信息：

<img width="799" alt="屏幕快照 2020-02-04 上午9 52 33" src="https://user-images.githubusercontent.com/5888974/73706976-04f18f80-4735-11ea-92e4-9c6be9bf17dc.png">

**Comment by afc163** [comment]
那个分支。

**Comment by paleface001** [comment]
g2plot master分支可复现

**Comment by afc163** [comment]
问题比较诡异。

**Comment by paleface001** [comment]
確かに 感觉像是gatby-theme的某个依赖出的问题，不然无法解释为啥之前的版本也不行了

**Comment by afc163** [comment]
https://github.com/gatsbyjs/gatsby/issues/20943#issuecomment-579367672

**Comment by afc163** [comment]
暂时锁定一下版本：https://github.com/antvis/G2Plot/pull/555 ，gatsby 新版有点问题，官方 issue 里跟踪 https://github.com/gatsbyjs/gatsby/issues/20943#issuecomment-581733538
