### ISSUE TITLE
make primary color consistent

### ISSUE THREAD

**Issue by geekplux** [antvis/gatsby-theme-antv#111]
I figured out someplace still use default color but primary color, it's better to make them consistent, what do you think?

https://github.com/antvis/gatsby-theme-antv/blob/68e5e5bd8d9daed7d9831d54bb4bf0e5389c01ee/%40antv/gatsby-theme-antv/site/components/Companies.module.less#L29
https://github.com/antvis/gatsby-theme-antv/blob/c3c8c75740688fe1e01975d241b5d7d78aeed72c/%40antv/gatsby-theme-antv/site/components/Features.module.less#L36

I would do a PR using `fade()` as other place if you think so.

**Comment by afc163** [comment]
PR is welcome~
