### ISSUE TITLE
文档链接问题

### ISSUE THREAD

**Issue by simaQ** [antvis/gatsby-theme-antv#114]
复现步骤：

1. 点击： https://g2.antv.vision/zh/docs/api/g2
2. 随便点击下右侧菜单目录
![image](https://user-images.githubusercontent.com/6628666/76132969-ac255780-6050-11ea-9975-f3dde717cb2b.png)

3. 然后点击超链接：

![image](https://user-images.githubusercontent.com/6628666/76132974-b5aebf80-6050-11ea-9c46-e67b3580f3fe.png)

生成的 URL 路径不对：https://g2.antv.vision/zh/docs/api/g2/interfaces/axiscfg 导致页面 404，这个链接正常的应该是 https://g2.antv.vision/zh/docs/api/interfaces/axiscfg

**Comment by afc163** [comment]
这要看你 md 源码怎么写的。
