### ISSUE TITLE
图表示例页面的代码编辑器功能诉求

### ISSUE THREAD

**Issue by baizn** [antvis/gatsby-theme-antv#115]
图表示例页面的代码编辑器功能诉求：
1、显示代码行数；
2、支持代码折叠。

![image](https://user-images.githubusercontent.com/9443867/76504831-62d76c80-6483-11ea-84eb-9ad2882b267f.png)

**Comment by afc163** [comment]
[0.10.62](https://github.com/antvis/gatsby-theme-antv/releases/tag/0.10.62) 已支持。
