### ISSUE TITLE
源码问题

### ISSUE THREAD

**Issue by Cratosw** [antvis/gatsby-theme-antv#116]
请问@antv/gatsby-theme-antv 这部分代码怎么运行起来？

**Comment by afc163** [comment]
`yarn start`

https://github.com/antvis/gatsby-theme-antv#develop

**Comment by Cratosw** [comment]
基于 gatsby-starter-theme-antv 生成的代码 gatsby develop 没问题，我的意思是想修改@antv/gatsby-theme-antv 中部分源码
