### ISSUE TITLE
网站英文页面图表顺序混乱

### ISSUE THREAD

**Issue by paleface001** [antvis/gatsby-theme-antv#120]
<img width="958" alt="屏幕快照 2020-03-31 下午5 50 31" src="https://user-images.githubusercontent.com/5888974/78013654-5e62ed00-7379-11ea-8ef1-f87c49bbfff4.png">

**Comment by afc163** [comment]
给个重现分支。

**Comment by paleface001** [comment]
G2Plot的master分支和网站现在可以复现了：
https://g2plot.antv.vision/en/examples/gallery
