### ISSUE TITLE
图标演示的演示二出错（ant design示例)

### ISSUE THREAD

**Issue by rainsoft** [antvis/gatsby-theme-antv#123]
https://gatsby-starter-theme-antv.antv.vision/zh/examples/second
演示二出错，麻烦更新一下。

**Comment by afc163** [comment]
这是例子，特意写错的，验证代码有错误时的表现。

**Comment by rainsoft** [comment]
那能否写一个正确的，可以演示ant-design示例代码的例子？我试了试，发现总是不成功。

**Comment by doramart** [comment]
正确的应该是什么样的？@

> 这是例子，特意写错的，验证代码有错误时的表现。
