### ISSUE TITLE
gatsby-cli 版本问题导致的报错

### ISSUE THREAD

**Issue by lzxue** [antvis/gatsby-theme-antv#124]
网站启动报错 
![image](https://user-images.githubusercontent.com/4366658/79552885-3dff9600-80ce-11ea-8e5e-b4faaff35501.png)

同 https://github.com/gatsbyjs/gatsby/issues/23214

锁定 gatsby-cli@2.11.0 版本之后可正常使用

**Comment by afc163** [comment]
![image](https://user-images.githubusercontent.com/507615/79720855-f702e200-8313-11ea-91b5-e29fc036b821.png)
