### ISSUE TITLE
G2 升级至 0.9.34 后的一些反馈

### ISSUE THREAD

**Issue by simaQ** [antvis/gatsby-theme-antv#16]
- [x] 首页头部的连接被遮挡导致不可点击

![image](https://user-images.githubusercontent.com/6628666/68529290-12ff6200-0338-11ea-8ff0-c7593f96105a.png)

- [x] 文档页面前部出现了未知的空白

![2019-11-09 21-30-24 2019-11-09 21_31_31](https://user-images.githubusercontent.com/6628666/68529309-54900d00-0338-11ea-83ff-9995a406285f.gif)

- [x] 需求：G2 设计师完白大爷的设计稿里要求加一个继续下载按钮

![Snip20191109_5](https://user-images.githubusercontent.com/6628666/68529596-41cb0780-033b-11ea-8cfe-6c1df2d26a5b.png)

- [x] README 连接部分 404 
![Snip20191109_6](https://user-images.githubusercontent.com/6628666/68529633-91113800-033b-11ea-8e3c-85090170fe49.png)

- [x] 国际化方案没有生效捏...

![image](https://user-images.githubusercontent.com/6628666/68529867-e6e6df80-033d-11ea-9197-89e3c34c38ce.png)

**Comment by afc163** [comment]
- [ ] 继续了解后面的 GitHub stars 按钮也需要写一下。

**Comment by afc163** [comment]
- [ ] 首页的动画有点卡，CPU 飙的很高。

**Comment by afc163** [comment]
<img width="840" alt="图片" src="https://user-images.githubusercontent.com/507615/68531645-6e891a00-034f-11ea-9b1a-e3b8e90dcf2c.png">

我本地测试国际化是生效的。

**Comment by Yanyan-Wang** [comment]
> * [ ]  首页的动画非常卡，CPU 飙的很高，操作困难。

已改成 css 控制动画

**Comment by afc163** [comment]
> 首页头部的连接被遮挡导致不可点击

这个我也没有重现出来。

**Comment by afc163** [comment]
- [ ] 播放按钮没有 hover 反馈。
- [ ] 播放按钮应该放在所有按钮的右边。
- [ ] GitHub Stars 按钮的样式和设计不符。

<img width="620" alt="image" src="https://user-images.githubusercontent.com/507615/68564981-1d7f4000-048d-11ea-92f1-fb8318da7f99.png">

**Comment by afc163** [comment]
- [ ] 不要叫 downloadButton ，不应该限制用户的使用方式，改成这样的 API 会比较合适。另外这里不应该出现两个主按钮吧，具体样式咨询一下设计师。

```
buttons={[{ text: 'xxx', href: 'xxx', type: 'primary' }, { text: 'xxx', href: 'xxx', type: 'primary' }]}
```

**Comment by afc163** [comment]
动画还是有点卡，hover 卡片和链接的时候，响应感觉有点慢。

**Comment by Yanyan-Wang** [comment]
> * [ ]  播放按钮没有 hover 反馈。
> * [ ]  播放按钮应该放在所有按钮的右边。
> * [ ]  GitHub Stars 按钮的样式和设计不符。
> 
> <img alt="image" width="620" src="https://user-images.githubusercontent.com/507615/68564981-1d7f4000-048d-11ea-92f1-fb8318da7f99.png">

- 播放按钮应该放在所有按钮的右边：播放按钮只会在总的主页有，下载使用和 github 按钮只有子产品有。这两部分不会共存。
- 另外两个问题我晚点改一下

**Comment by Yanyan-Wang** [comment]
> * [ ]  不要叫 downloadButton ，不应该限制用户的使用方式，改成这样的 API 会比较合适。另外这里不应该出现两个主按钮吧，具体样式咨询一下设计师。
> 
> ```js-jsx
> buttons={[
>   { text: 'xxx', href: 'xxx', type: 'primary' }, 
>   { text: 'xxx', href: 'xxx', type: 'primary' },
> ]}
> ```

好的。因为主页没有下载使用按钮，所以这个按钮的样式可以从外部传入，可以让子产品页面传自己的样式。

**Comment by afc163** [comment]
buttonText/buttonHref/downloadButton 都合并为 buttons，video 和 githubStar 没什么问题。

**Comment by afc163** [comment]
- [ ] `githubStarLink` 改成 `showGithubStar`，Boolean 类型，默认为 true。地址不需要用户传，直接读配置中的 githubUrl，类似右上角 GitHub 的地址的读取。
