### ISSUE TITLE
playground 支持一下 typescript 和 智能提示

### ISSUE THREAD

**Issue by bubkoo** [antvis/gatsby-theme-antv#184]
使用 monaco 编辑器吧

**Comment by afc163** [comment]
monaco 太重了。

**Comment by afc163** [comment]
支持 TS 的：https://github.com/antvis/gatsby-theme-antv/blob/master/example/examples/basic/demo/ts-demo.ts

**Comment by afc163** [comment]
close in https://github.com/antvis/gatsby-theme-antv/pull/195
