### ISSUE TITLE
Add copyright notice to license

### ISSUE THREAD

**Issue by balibebas** [antvis/gatsby-theme-antv#189]
This is a great theme but as it stands the work added to the _gatsbyjs_ work is unclear from a licensing perspective given no copyright notice was added by the author. Please add a copyright notice. For more information see: https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html. If you're unsure how to add a notice let me know and I'll help.

Related: https://github.com/gatsbyjs/gatsby/issues/25091

**Comment by afc163** [comment]
https://github.com/antvis/gatsby-theme-antv/blob/f57ffb8134128def5f536f54952994137c56f41b/LICENSE#L3-L21

**Comment by balibebas** [comment]
I don't think you understood the issue. If you decide you'd like to better understand it, please feel free to respond. I'm still subscribed. And the issue persists. Gatsby did end up changing their license as a result of my feedback but that was after this code was forked.

**Comment by afc163** [comment]
Thx for tips. https://github.com/antvis/gatsby-theme-antv/commit/f2b73ed2c62fe98bd0fe94548a517ac5e69f15c1
