### ISSUE TITLE
支持在文档中插入 code playground

### ISSUE THREAD

**Issue by afc163** [antvis/gatsby-theme-antv#190]

**Comment by afc163** [comment]
实现方式可参考：https://github.com/antvis/gatsby-theme-antv/pull/119

**Comment by afc163** [comment]
这个还蛮有用的，可以在 11.22 前搞一搞，给每个库的『上手文档』都加个初始例子。

**Comment by BBSQQ** [comment]
> 这个还蛮有用的，可以在 11.22 前搞一搞，给每个库的『上手文档』里都加个初始例子。

好的

**Comment by afc163** [comment]
https://x6.antv.vision/zh/docs/tutorial/getting-started

UI 和 loading 可以参考一下 x6 这里的样式，做的很漂亮。

**Comment by BBSQQ** [comment]
> https://x6.antv.vision/zh/docs/tutorial/getting-started
> 
> UI 可以参考一下 x6 这里的样式，做的很漂亮。
> 
> <img alt="image" width="1206" src="https://user-images.githubusercontent.com/507615/97149266-7aabf880-17a7-11eb-9386-bbcccfa0a65c.png">
> 
> * [ ]  支持 loading - 现在代码块执行挺快的，不需要 loading
> * [ ]  支持默认不展现代码区域 - 我认为可以加默认的代码块，这里两个作用看代码和看预览效果
> * [ ]  样式优化
> * [ ]  README 用法里补一个截图 - done

我现在给 pageLoading 加了 x6 的效果
https://antvis-gatsby-theme-antv-preview-pr-231.surge.sh/en

**Comment by afc163** [comment]
已实现：https://github.com/antvis/gatsby-theme-antv/pull/225
