### ISSUE TITLE
API 部分抽取公共内容，md 自动填充

### ISSUE THREAD

**Issue by BBSQQ** [antvis/gatsby-theme-antv#203]
内网👇：https://yuque.antfin-inc.com/antv/rkzcpd/lwseu8
# API md 自动生成

## 背景描述
现状：AntV 官网目前所有页面都是通过 md 自动生成的，如下图，右侧的层级结构是 md 的 n级标题：
![image](https://user-images.githubusercontent.com/35586469/89293428-7ed8e600-d690-11ea-811c-c4021d9557cf.png)

痛点：一个类库有很多同样的描述，比如折线图、散点图都会有描述绘图元素的 style，那我如果之后需要改这部分内容就需要像下面一样，改几十个 md 文件，这样手动维护成本太高了
![image](https://user-images.githubusercontent.com/35586469/89293462-8bf5d500-d690-11ea-900b-3bc64d82a216.png)

## 需求

- 维持现有网站解析 md 的模式
- 公共的内容 md 只写一份
- 主体结构的 md 可以引用 公共内容 md

例子如下：
公共内容 md，以 `style`  为例
```markdown
## style
### fill
填充

### stroke 
描边
```

主体内容 md，以 `折线图` 为例
```markdown
## 折线图

### xField
x轴

### yField
y轴

### lineStyle (quote style)
这里可以通过脚本自动添加公共内容文件 style 里的内容
```

**Comment by NewByVector** [comment]
![image](https://user-images.githubusercontent.com/20186737/89772617-e7164480-db34-11ea-998d-d3264364091e.png)
![image](https://user-images.githubusercontent.com/20186737/89772636-f09fac80-db34-11ea-8f72-6e6f1a5433c5.png)
遍历当前页面内容ast，遇到自定义的标签(hello)就替换为对应路径md文档的ast。 功能可行，实现起来感觉比较粗鲁
