### ISSUE TITLE
footer页脚怎么custom？

### ISSUE THREAD

**Issue by littleboss** [antvis/gatsby-theme-antv#204]
想用自己的footer，但是看了下是写死再layout里面的

**Comment by littleboss** [comment]
@afc163 thanks, i got your update

**Comment by littleboss** [comment]
how can i remove the products of the footer and then customize?

**Comment by afc163** [comment]
Upgrade to https://github.com/antvis/gatsby-theme-antv/releases/tag/0.11.2, and see https://github.com/antvis/gatsby-theme-antv#how-to-customise-layout-footer
