### ISSUE TITLE
import css from node_modules

### ISSUE THREAD

**Issue by bubkoo** [antvis/gatsby-theme-antv#215]
支持样式引入

```ts
import { Graph } from '@antv/x6'
import '@antv/x6/es/index.css'
```

**Comment by afc163** [comment]
需要在哪里引入？

**Comment by bubkoo** [comment]
![image](https://user-images.githubusercontent.com/6045824/90597891-87025b00-e224-11ea-9c0c-4047c6ae5a58.png)

**Comment by afc163** [comment]
x6 的样式最好能走 css-in-js，引入方便，定制样式也对用户比较友好。
