### ISSUE TITLE
右侧的导航再紧凑一点吧，说好的参考语雀呢

### ISSUE THREAD

**Issue by bubkoo** [antvis/gatsby-theme-antv#244]
我们的 
![image](https://user-images.githubusercontent.com/6045824/98221076-2adce680-1f8a-11eb-9a89-2cd3ad0a66e9.png)
![image](https://user-images.githubusercontent.com/6045824/98221108-329c8b00-1f8a-11eb-9eae-7b01eae4e8c7.png)

语雀的

![image](https://user-images.githubusercontent.com/6045824/98221001-113b9f00-1f8a-11eb-9a36-ff718fca8079.png)

**Comment by afc163** [comment]
+1

**Comment by afc163** [comment]
右侧锚点列表也需要紧凑一点：

<img width="268" alt="image" src="https://user-images.githubusercontent.com/507615/98222433-c7ec4f00-1f8b-11eb-92c2-f36136099cc5.png">
