### ISSUE TITLE
1.0.0 新版本问题统一汇总 & 新功能预告 & 已上线功能

### ISSUE THREAD

**Issue by BBSQQ** [antvis/gatsby-theme-antv#245]
> 花名引路
@xingwanying 缨缨
@NewByVector 文瑀
@BBSQQ 羽熙

issues:
- [x] P0 markdown 文档样式统一优化 @BBSQQ 
- [x] P0 start 之后修改不生效 crash https://github.com/antvis/gatsby-theme-antv/issues/248 @NewByVector 
- [x] P0 右侧目录树对标 yuque 样式优化 https://github.com/antvis/gatsby-theme-antv/issues/244 @NewByVector 
- [ ] P1 分类 demo 英文名重复导致锚点重复 gallery 分类错误（建议先手动修改避免重复）
- [ ] P1 markdown 中插入除现有 demo 之外的独立示例

-------
待上线功能：
- [x] G2 G2Plot 色板小工具 @xingwanying 

------
已上线功能：
* 编辑器提示增强，需要加 api-extractor，具体细节可以找 @NewByVector 
* 支持 markdown 内容引用 @NewByVector 
* 交互式文档页面 UI 交互 @xingwanying 
* markdown 文档内容或者 交互式文档页面 api 内容解析出错 @NewByVector 
* G2Plot 项目启动慢 @NewByVector 
* markdown 中插入 demo @BBSQQ 
* markdown 目录锚点 @NewByVector 
* gallery 滚动锚点 @NewByVector 
* Editor 远程请求数据展示数据格式 @NewByVector

**Comment by hustcc** [comment]
- [ ] 文档页面刷新会自动后面加 / ，导致 404
 - [ ] 点击到 demo 页面的时候，空白
 - [ ] 缺失 404 页面
 - [ ] playground 是否可以引入非 demo 的代码片段

**Comment by afc163** [comment]
已上线功能补充：

- https://github.com/antvis/gatsby-theme-antv/pull/240
- https://github.com/antvis/gatsby-theme-antv/pull/230

**Comment by BBSQQ** [comment]
> * [x]  文档页面刷新会自动后面加 / ，导致 404 ➡️ 先写绝对路径避免吧，我本地没复现
> * [x]  点击到 demo 页面的时候，空白 ➡️  开发时候偶然出现，先记下来了，优先级较低
> * [x]  缺失 404 页面 ➡️  404 一直都有啊，你打开这个看看 https://g2plot.antv.vision/zh/docs/aaa

> * [x]  playground 是否可以引入非 demo 的代码片段 -已加入上面功能

@NewByVector 强哥手把手看看编辑器相关的能力吧
> * [ ]  编辑器提示没有了
> * [ ]  编辑器 redo undo 没有了
> * [ ]  编辑器偶现，运行的内容不是输入框中的内容，感觉是 debounce 使用不当的问题

**Comment by BBSQQ** [comment]
![image](https://user-images.githubusercontent.com/35586469/98544966-b11d6380-22cf-11eb-8899-5b08444a84ae.png)
