### ISSUE TITLE
example 侧边栏不能重名

### ISSUE THREAD

**Issue by bubkoo** [antvis/gatsby-theme-antv#284]
比如节点下面有个「工具」栏目，边下面也有一个「工具」栏目。
现在非要命名为不同的名称。
![image](https://user-images.githubusercontent.com/6045824/102894818-a34a2900-449e-11eb-947b-1876c1d4b4d9.png)

**Comment by bubkoo** [comment]
有没有雷锋支持一下？

**Comment by BBSQQ** [comment]
1122 前已知问题，强哥接着跟进一下吧
