### ISSUE TITLE
这里的 issue 貌似没人关注啊，改一个 issue 提升所有官网的体验，不香吗？

### ISSUE THREAD

**Issue by bubkoo** [antvis/gatsby-theme-antv#287]
一个个 issue 起码都一周以上没有人关注，也没人回复。

**Comment by BBSQQ** [comment]
崖哥，没有不关注，只是这个评估下来可能挺难改的，现在官网编辑器文件解析太重了，demo 一多就解析不更新，感觉要改需要整体梳理一下。如果可以的话，求指导🥺 @bubkoo @afc163

**Comment by BBSQQ** [comment]
![image](https://user-images.githubusercontent.com/35586469/103441158-f6825f80-4c86-11eb-8bc7-02fe4c630a55.png)

之后会每周跟进的，issue 先关了

**Comment by afc163** [comment]
@bubkoo 直接 PR 吧。
