### ISSUE TITLE
如图：为什么要留 64px (切换到移动版视图，没有这个问题，视觉上更好)

### ISSUE THREAD

**Issue by visiky** [antvis/gatsby-theme-antv#289]
![image](https://user-images.githubusercontent.com/15646325/103467756-23209f00-4d8d-11eb-92f4-fbfacb29cf6d.png)

**Comment by xingwanying** [comment]
solved

**Comment by afc163** [comment]
在 git commit message 里关联一下 issue。

**Comment by xingwanying** [comment]
> 在 git commit message 里关联一下 issue。

是前几个版本的commit，才看到的issue……

**Comment by afc163** [comment]
可以去对应 commit 里回复一个这个 issue 的链接，这样也能关联到。
