### ISSUE TITLE
是否支持绝对路径引用文档

### ISSUE THREAD

**Issue by Me-Momo** [antvis/gatsby-theme-antv#290]
![image](https://user-images.githubusercontent.com/15646325/103496540-9d2e5200-4e79-11eb-88d8-c7c283fc8b69.png)

**Comment by Me-Momo** [comment]
是否有雷锋支持下（或者指导下应该怎么处理）

**Comment by hustcc** [comment]
现在 G2 G2Plot 文档全部抽出可以复用的 common md 文件，但是如果引用路径使用相对路径的话，会导致在不同层级下这个相对目录一定带来 404。

**Comment by BBSQQ** [comment]
![image](https://user-images.githubusercontent.com/35586469/103529970-9a574f80-4ec1-11eb-8153-6fa6c2542c43.png)

参考 G6 这种写法，即可绝对路径 @hustcc @Me-Momo

**Comment by Me-Momo** [comment]
哦哦 需要加上 zh? 和 en?  就好了是吧

**Comment by Me-Momo** [comment]
nice 加上“国际化”的前缀就解决了

**Comment by hustcc** [comment]
> 哦哦 需要加上 zh? 和 en? 就好了是吧

@BBSQQ 带上根路径的国际化前缀的话，那不是强制用户使用某一个语言，而不是跟随用户的国际化配置。

**Comment by BBSQQ** [comment]
> > 哦哦 需要加上 zh? 和 en? 就好了是吧
> 
> @BBSQQ 带上根路径的国际化前缀的话，那不是强制用户使用某一个语言，而不是跟随用户的国际化配置。

markdown 里的链接也就是和 a 标签一个作用，/ 即是从网站根路由开始，至于多语言，其实本来也应该写两套的，即使是 common 公共引用，也应该 en zh 分别写的，这样才可以在两种语言环境下获取到不同的内容。

**Comment by BBSQQ** [comment]
推荐中英文都写内容，如果不想写，英文就复制一份中文的吧🤭
