### ISSUE TITLE
跪求优化下拉搜索 🔍（现在的检索真的没有以前好用啊）

### ISSUE THREAD

**Issue by visiky** [antvis/gatsby-theme-antv#291]
现在的检索真的没有以前好用啊，没有行为记忆点，每次下滑找了很久， popover 还会不小心弹回去，太难使用了

- [x] https://github.com/antvis/G2Plot/discussions/2614

![image](https://user-images.githubusercontent.com/15646325/103714068-b7db0500-4ff8-11eb-8748-8d1b401b9a97.png)

**Comment by fadeed** [comment]
好，马上跟进

**Comment by BBSQQ** [comment]
> 好，马上跟进解决（近期上线

这位雷锋报下大名？我们有新的设计方案，可否有时间支持一下？🤓

**Comment by wo8335224** [comment]
我也跪求！！！这个是不是凉了···

**Comment by xingwanying** [comment]
> 我也跪求！！！这个是不是凉了···

安排中，近期会上线

**Comment by visiky** [comment]
尝试下 1.1.6-beta.5 ，应该可以了；G2Plot 官网已经使用上了
