### ISSUE TITLE
【bug】gallery demo 页面移动端适配

### ISSUE THREAD

**Issue by BBSQQ** [antvis/gatsby-theme-antv#292]
gallery  页面布局显示问题
![image](https://user-images.githubusercontent.com/35586469/103843120-35267880-50d2-11eb-880c-09b0ae50b886.png)

demo 在移动端没有显示出来
![image](https://user-images.githubusercontent.com/35586469/103843155-466f8500-50d2-11eb-9170-3ba2f9b5ca48.png)

**Comment by xingwanying** [comment]
已解决
