### ISSUE TITLE
能去除底部footer的product吗？有办法吗？？或者可以配置吗

### ISSUE THREAD

**Issue by wo8335224** [antvis/gatsby-theme-antv#298]
如下这些东西。

G2可视化引擎
产品首页
图表示例
使用文档
API 文档
更新日志
GitHub 仓库
🇨🇳国内镜像
F2移动可视化方案
产品首页
图表示例
使用文档
API 文档
更新日志
GitHub 仓库
🇨🇳国内镜像
G6图可视化引擎
产品首页
图表示例
使用文档
API 文档
更新日志
GitHub 仓库
🇨🇳国内镜像
X6图编辑引擎
产品首页
图表示例
使用文档
API 文档
GitHub 仓库
🇨🇳国内镜像
L7地理空间数据可视化
产品首页
图表示例
使用文档
API 文档
更新日志
GitHub 仓库
🇨🇳国内镜像
G2Plot开箱即用的图表库
产品首页
图表示例
使用文档
API 文档
更新日志
GitHub 仓库
🇨🇳国内镜像
F2Native移动可视化方案
产品首页
图表示例
使用文档
API 文档
GitHub 仓库
🇨🇳国内镜像
Graphin
产品首页
组件示例
使用文档
API 文档
更新日志
GitHub 仓库
🇨🇳国内镜像
AVA
产品首页
图表示例
使用文档
API 文档
GitHub 仓库
🇨🇳国内镜像
ChartCube图表魔方
产品首页
生成图表
语雀社区
钉钉

**Comment by afc163** [comment]
https://github.com/antvis/gatsby-theme-antv#how-to-customise-layout-footer
