### ISSUE TITLE
怎么修改logo和logo链接，怎么去掉footer

### ISSUE THREAD

**Issue by yangfjiahl** [antvis/gatsby-theme-antv#325]
怎么修改logo和logo链接，怎么去掉footer

**Comment by xingwanying** [comment]
1. 修改logo：
https://github.com/antvis/gatsby-theme-antv
![image](https://user-images.githubusercontent.com/10885578/118425355-9fdc6600-b6fb-11eb-992d-e251e6547af7.png)

2. 如果要自定义页面布局，可以用独立页面，按需引入需要的组件：
https://github.com/antvis/antvis.github.io/issues/18#issuecomment-568692771
![image](https://user-images.githubusercontent.com/10885578/118425515-ecc03c80-b6fb-11eb-9828-a808a418285d.png)

**Comment by chenyijie-bit** [comment]
修改logo的 跳转 跳转 跳 转地址怎么做的 ？ 你这不是只回答了修改logo的地址吗？
