### ISSUE TITLE
编辑器问题

### ISSUE THREAD

**Issue by visiky** [antvis/gatsby-theme-antv#329]
记录一些问题：

|||
|---|---|
|![image](https://user-images.githubusercontent.com/15646325/119436854-8f596a80-bd4f-11eb-9193-6f28dc293221.png)||
![image](https://user-images.githubusercontent.com/15646325/119437017-d7788d00-bd4f-11eb-8a95-ce94e3f0d962.png)||
|![image](https://user-images.githubusercontent.com/15646325/120422950-04562100-c39c-11eb-89c6-f8ae88d19e1e.png)||
|![image](https://user-images.githubusercontent.com/15646325/123775604-19719180-d901-11eb-95fe-9b42c7948bd3.png)| 1. 刷新页面无法解决，执行下 localStorage.clear(), 再刷新页面可以解决 2. 如何复现，不知道（看下代码哪里写了 localStorage） |

**Comment by lxfu1** [comment]
编辑器无法滚动到顶部： 
![image](https://user-images.githubusercontent.com/31396322/120762757-217c2280-c549-11eb-9c8d-487a5728ef7d.png)

复现链接： https://g2.antv.vision/zh/examples/other/other#word-cloud

**Comment by visiky** [comment]
@ai-qing-hai 这个问题还存在

![image](https://user-images.githubusercontent.com/15646325/124343005-f560c980-dbfa-11eb-9fbd-28d377ccafc8.png)
