### ISSUE TITLE
WebpackError: ReferenceError: gatsby_1 is not defined

### ISSUE THREAD

**Issue by dengfuping** [antvis/gatsby-theme-antv#6]
## Version

- 0.5.6

## Screen Shot
![image](https://user-images.githubusercontent.com/14918822/67844016-f85b0b00-fb37-11e9-86fb-2588dbe797be.png)

## Reproducible link

- https://app.netlify.com/sites/antv-g/deploys/5db933b55034d06e5e7c717c

**Comment by afc163** [comment]
还是要用回 `@antv/gatsby-theme-antv/site/components/Seo`

https://github.com/antvis/gatsby-theme-antv/pull/7/commits/edc4907f8c869444e9e74f38f68c4272d720f11a
