### ISSUE TITLE
文档阅读时间问题

### ISSUE THREAD

**Issue by simaQ** [antvis/gatsby-theme-antv#68]
目前看了 G2 和 G6 两个产品的网站，英文文档显示的都是正常的，但是中文文档显示的都有问题：

1. G2 的中文文档在分钟数大于 10 的情况下显示的结果错乱  https://github.com/antvis/g2/issues/1719

https://g2.antv.vision/zh/docs/api/chart

![image](https://user-images.githubusercontent.com/6628666/69780899-8a157100-11e7-11ea-8b2e-5fcda0450e67.png)

2. G6 的中文文档则全部显示为 1 分钟

![image](https://user-images.githubusercontent.com/6628666/69780921-9e596e00-11e7-11ea-9b40-3ef88e05c6f4.png)

**Comment by afc163** [comment]
@antv/gatsby-theme-antv@0.10.6
