### ISSUE TITLE
演示代码本地修改后刷新不生效

### ISSUE THREAD

**Issue by afc163** [antvis/gatsby-theme-antv#69]

**Comment by afc163** [comment]
测试了一下主题里是生效的，但是 graphin 下会慢一拍，就是修改后上一次修改的才会生效。原因排查中...

**Comment by simaQ** [comment]
上周也发现了这个问题~~~ 本地代码修改后，即使手动刷新刷新了也不生效

**Comment by afc163** [comment]
Fixed in `@antv/gatsby-theme-antv@0.10.10`
