### ISSUE TITLE
带有中划线(-)的包名，挂载到 window 对象后无法 import

### ISSUE THREAD

**Issue by dengfuping** [antvis/gatsby-theme-antv#80]
- 对于 G 来说，现在是两个独立的包名，`@antv/g-canvas` 和 `@antv/g-svg`。在 `gatsby-config.js` 中按照以下配置:
```js
window['g-canvas'] = require('./packages/g-canvas/src/index.ts');
// or
window['@antv/g-canvas'] = require('./packages/g-canvas/src/index.ts');

```
- 在 `demo` 代码中都无法 import:
```js
import { Canvas } from '@antv/g-canvas'; 
```

![image](https://user-images.githubusercontent.com/14918822/70702718-acd87700-1d09-11ea-8c3a-947f675d8e8a.png)

- 包名换成 `g` 或者 `g_canvas` 都是可以正确 import 的，但中划线分隔的包名就报错。

![image](https://user-images.githubusercontent.com/14918822/70702896-02ad1f00-1d0a-11ea-977a-949de3ae2fb5.png)

**Comment by afc163** [comment]
需要 `window.gCanvas = require('./packages/g-canvas/src/index.ts');` 这么传递一下。

**Comment by dengfuping** [comment]
可以了 👍

**Comment by afc163** [comment]
<img width="816" alt="图片" src="https://user-images.githubusercontent.com/507615/71447319-c648dc80-2767-11ea-9964-0f7d180e403b.png">
<img width="821" alt="图片" src="https://user-images.githubusercontent.com/507615/71447322-cc3ebd80-2767-11ea-958c-59c31c75b07e.png">


https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=usage&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAMQExwGZQiOByAAgQwDsYA3AelSWwG4AoUSWOAdwAt8YBTEzqNDLHiKky-fAFoARpJr1w0eACVO-AMYwAIgHkAsv0w4oK9eIAmmWQwVxla-OgPYjd2bVURCAZwgAbTgDofCABzAApkABobY01dKNt1AEpqIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Ctypescript%2Cenv&prettier=false&targets=&version=7.7.4&externalPlugins=%40babel%2Fplugin-transform-modules-umd%407.7.4
