### ISSUE TITLE
菜单配置考虑支持iframe内嵌模式

### ISSUE THREAD

**Issue by janryWang** [antvis/gatsby-theme-antv#82]
因为有些场景需要直接内嵌第三方页面

**Comment by afc163** [comment]
没懂，哪个菜单，菜单和 iframe 的关系是？

**Comment by janryWang** [comment]
> 没懂，哪个菜单，菜单和 iframe 的关系是？

就是metaData里的navs，可以直接配远程链接，以iframe形式来展示

**Comment by afc163** [comment]
https://graphin.antv.vision/zh/GraphinStudio

这个不就是？

**Comment by janryWang** [comment]
https://github.com/antvis/gatsby-theme-antv/blob/master/example/gatsby-config.js#L13 这个例子里面没看到怎么使用iframe的诶

**Comment by afc163** [comment]
可以参考一下  Graphin 的写法：

- menu 定义：https://github.com/antvis/Graphin/blob/5a8ebfbc5047c4faa4066b84557827869d01f41a/packages/graphin-site/gatsby-config.js#L35
- iframe 页面：https://github.com/antvis/Graphin/blob/5a8ebfbc5047c4faa4066b84557827869d01f41a/packages/graphin-site/site/pages/GraphinStudio.zh.tsx#L19

如果这个页面不需要统一导航，可以指定 `noLayout` https://github.com/antvis/gatsby-theme-antv/blob/f5f3b77c5d297a4e46bbd4d0a1c4f4e8c524bdca/example/site/pages/independent.zh.tsx#L9

**Comment by janryWang** [comment]
意思是，只要写在pages目录里的React组件都能自动读到？

**Comment by afc163** [comment]
https://www.gatsbyjs.org/docs/recipes/#creating-pages-automatically
