### ISSUE TITLE
gatsby-config.js里插件配置主题色不生效

### ISSUE THREAD

**Issue by PhotoArtLife** [antvis/gatsby-theme-antv#90]
![image](https://user-images.githubusercontent.com/8949357/71443519-51b17600-2746-11ea-848c-a8c4de6fe092.png)
- 按照官方提供的plugins配置，自定义主题覆盖ant theme的primary-color，视觉上没有生效。

**Comment by afc163** [comment]
给个重现 repo？

**Comment by PhotoArtLife** [comment]
> 给个重现 repo？

暂时没放到外网（github之类的）目前仅打算部署在内网

**Comment by afc163** [comment]
你属性位置配置错了，请参考 https://github.com/antvis/gatsby-theme-antv#gatsby-configjs

**Comment by PhotoArtLife** [comment]
> > 给个重现 repo？
> 
> 暂时没放到外网（github之类的）目前仅打算部署在内网

我稍后给你发邮件~

**Comment by afc163** [comment]
Released in https://github.com/antvis/gatsby-theme-antv/releases/tag/0.10.33
