### ISSUE TITLE
Banner组件button type及Icon组件部分style样式没有主题配置关联

### ISSUE THREAD

**Issue by PhotoArtLife** [antvis/gatsby-theme-antv#92]
业务层自定义site/index.zh.tsx，遇到的issue：

https://github.com/antvis/gatsby-theme-antv/blob/master/%40antv/gatsby-theme-antv/site/components/Banner.tsx

1. ButtonLink组件目前只支持primary和非primary，buttons map 的array没有render antd button组件，所以在业务方配置bannerButtons时（比如指定别的type：warning） 此处button视觉不生效，建议可以内嵌antd button，便于配置和props共享。

![image](https://user-images.githubusercontent.com/8949357/71466147-aa8e1680-27f9-11ea-8dac-db1224b9cd2e.png)
![image](https://user-images.githubusercontent.com/8949357/71466281-13758e80-27fa-11ea-9688-c5623a1fc48e.png)

2. 第141行 Icon组件的props style 没必要传写死的color属性了 便于走主题配置

![image](https://user-images.githubusercontent.com/8949357/71466392-5e8fa180-27fa-11ea-8886-317f9ea93fb9.png)

PS. 本来想给学长提PR的 权限摸索中~ 😄

**Comment by afc163** [comment]
来个 PR 吧，不难解决

**Comment by PhotoArtLife** [comment]
> 来个 PR 吧，不难解决
😄 好的 最近几天抽空提下~
