### ISSUE TITLE
页面定位的动画是否可以关闭？

### ISSUE THREAD

**Issue by simaQ** [antvis/gatsby-theme-antv#93]
https://g2.antv.vision/zh/docs/api/geometry/#label-%E9%85%8D%E7%BD%AE%E9%A1%B9

点击右侧导航，页面在滚动过程中会进行不必要的动画... 感觉太浪费时间了... 建议关闭动画，直接定位。

**Comment by afc163** [comment]
Chrome 的 `scroll-behavior: smooth` 时间确实有点漫长。

**Comment by afc163** [comment]
https://stackoverflow.com/questions/56069371/how-to-set-the-speed-of-the-smooth-scrolling-with-css

这个属性还不好调整，可以暂时覆盖解决。

```css
html {
  scroll-behavior: auto;
}
```

**Comment by simaQ** [comment]
> https://stackoverflow.com/questions/56069371/how-to-set-the-speed-of-the-smooth-scrolling-with-css
> 
> 这个速度还没办法用 css 调整，可以暂时覆盖样式去掉动画解决。
> 
> ```css
> html {
>   scroll-behavior: auto;
> }
> ```

好的。
