### ISSUE TITLE
产品首页按钮样式突变！

### ISSUE THREAD

**Issue by simaQ** [antvis/gatsby-theme-antv#95]
@antv/gatsby-theme-antv  0.10.36  版本。

如图：

![image](https://user-images.githubusercontent.com/6628666/71791143-d36ea100-306e-11ea-8491-8a56a762eedb.png)

**Comment by afc163** [comment]
my bad

**Comment by afc163** [comment]
`+ @antv/gatsby-theme-antv@0.10.37`
